package demo.ssm.pojo;

public class SC extends SCKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc.Grade
     *
     * @mbggenerated Sun Nov 06 23:39:07 CST 2022
     */
    private Integer grade;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc.Grade
     *
     * @return the value of sc.Grade
     *
     * @mbggenerated Sun Nov 06 23:39:07 CST 2022
     */
    public Integer getGrade() {
        return grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc.Grade
     *
     * @param grade the value for sc.Grade
     *
     * @mbggenerated Sun Nov 06 23:39:07 CST 2022
     */
    public void setGrade(Integer grade) {
        this.grade = grade;
    }
}