package demo.ssm.pojo;

public class SCKey {

    public SCKey(Integer sno, Integer cno) {
        this.sno = sno;
        this.cno = cno;
    }

    public SCKey() {
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc.Sno
     *
     * @mbggenerated Sun Nov 06 23:39:07 CST 2022
     */
    private Integer sno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc.Cno
     *
     * @mbggenerated Sun Nov 06 23:39:07 CST 2022
     */
    private Integer cno;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc.Sno
     *
     * @return the value of sc.Sno
     *
     * @mbggenerated Sun Nov 06 23:39:07 CST 2022
     */
    public Integer getSno() {
        return sno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc.Sno
     *
     * @param sno the value for sc.Sno
     *
     * @mbggenerated Sun Nov 06 23:39:07 CST 2022
     */
    public void setSno(Integer sno) {
        this.sno = sno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc.Cno
     *
     * @return the value of sc.Cno
     *
     * @mbggenerated Sun Nov 06 23:39:07 CST 2022
     */
    public Integer getCno() {
        return cno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc.Cno
     *
     * @param cno the value for sc.Cno
     *
     * @mbggenerated Sun Nov 06 23:39:07 CST 2022
     */
    public void setCno(Integer cno) {
        this.cno = cno;
    }
}