package demo.ssm.pojo;

public class TCKey {

    public TCKey(Integer cno, Integer teaId) {
        this.cno = cno;
        this.teaId = teaId;
    }

    public TCKey() {
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tc.Cno
     *
     * @mbggenerated Fri Nov 11 14:07:51 CST 2022
     */
    private Integer cno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tc.tea_id
     *
     * @mbggenerated Fri Nov 11 14:07:51 CST 2022
     */
    private Integer teaId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tc.Cno
     *
     * @return the value of tc.Cno
     *
     * @mbggenerated Fri Nov 11 14:07:51 CST 2022
     */
    public Integer getCno() {
        return cno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tc.Cno
     *
     * @param cno the value for tc.Cno
     *
     * @mbggenerated Fri Nov 11 14:07:51 CST 2022
     */
    public void setCno(Integer cno) {
        this.cno = cno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tc.tea_id
     *
     * @return the value of tc.tea_id
     *
     * @mbggenerated Fri Nov 11 14:07:51 CST 2022
     */
    public Integer getTeaId() {
        return teaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tc.tea_id
     *
     * @param teaId the value for tc.tea_id
     *
     * @mbggenerated Fri Nov 11 14:07:51 CST 2022
     */
    public void setTeaId(Integer teaId) {
        this.teaId = teaId;
    }
}