package demo.ssm.pojo;

public class Teacher {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.tea_id
     *
     * @mbggenerated Wed Nov 09 21:52:32 CST 2022
     */
    private Integer teaId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.tea_name
     *
     * @mbggenerated Wed Nov 09 21:52:32 CST 2022
     */
    private String teaName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.tea_sex
     *
     * @mbggenerated Wed Nov 09 21:52:32 CST 2022
     */
    private String teaSex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.tea_age
     *
     * @mbggenerated Wed Nov 09 21:52:32 CST 2022
     */
    private Integer teaAge;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.tea_tel
     *
     * @mbggenerated Wed Nov 09 21:52:32 CST 2022
     */
    private String teaTel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.tea_dept
     *
     * @mbggenerated Wed Nov 09 21:52:32 CST 2022
     */
    private String teaDept;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.tea_id
     *
     * @return the value of teacher.tea_id
     *
     * @mbggenerated Wed Nov 09 21:52:32 CST 2022
     */
    public Integer getTeaId() {
        return teaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.tea_id
     *
     * @param teaId the value for teacher.tea_id
     *
     * @mbggenerated Wed Nov 09 21:52:32 CST 2022
     */
    public void setTeaId(Integer teaId) {
        this.teaId = teaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.tea_name
     *
     * @return the value of teacher.tea_name
     *
     * @mbggenerated Wed Nov 09 21:52:32 CST 2022
     */
    public String getTeaName() {
        return teaName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.tea_name
     *
     * @param teaName the value for teacher.tea_name
     *
     * @mbggenerated Wed Nov 09 21:52:32 CST 2022
     */
    public void setTeaName(String teaName) {
        this.teaName = teaName == null ? null : teaName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.tea_sex
     *
     * @return the value of teacher.tea_sex
     *
     * @mbggenerated Wed Nov 09 21:52:32 CST 2022
     */
    public String getTeaSex() {
        return teaSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.tea_sex
     *
     * @param teaSex the value for teacher.tea_sex
     *
     * @mbggenerated Wed Nov 09 21:52:32 CST 2022
     */
    public void setTeaSex(String teaSex) {
        this.teaSex = teaSex == null ? null : teaSex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.tea_age
     *
     * @return the value of teacher.tea_age
     *
     * @mbggenerated Wed Nov 09 21:52:32 CST 2022
     */
    public Integer getTeaAge() {
        return teaAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.tea_age
     *
     * @param teaAge the value for teacher.tea_age
     *
     * @mbggenerated Wed Nov 09 21:52:32 CST 2022
     */
    public void setTeaAge(Integer teaAge) {
        this.teaAge = teaAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.tea_tel
     *
     * @return the value of teacher.tea_tel
     *
     * @mbggenerated Wed Nov 09 21:52:32 CST 2022
     */
    public String getTeaTel() {
        return teaTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.tea_tel
     *
     * @param teaTel the value for teacher.tea_tel
     *
     * @mbggenerated Wed Nov 09 21:52:32 CST 2022
     */
    public void setTeaTel(String teaTel) {
        this.teaTel = teaTel == null ? null : teaTel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.tea_dept
     *
     * @return the value of teacher.tea_dept
     *
     * @mbggenerated Wed Nov 09 21:52:32 CST 2022
     */
    public String getTeaDept() {
        return teaDept;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.tea_dept
     *
     * @param teaDept the value for teacher.tea_dept
     *
     * @mbggenerated Wed Nov 09 21:52:32 CST 2022
     */
    public void setTeaDept(String teaDept) {
        this.teaDept = teaDept == null ? null : teaDept.trim();
    }

}